export const FISH_DATA_REQUEST = 'FISH_DATA_REQUEST';
export const FISH_DATA_SUCCESS = 'FISH_DATA_SUCCESS';
export const FISH_DATA_FAIL = 'FISH_DATA_FAIL';
export const FISH_LIST_REQUEST = 'FISH_LIST_REQUEST';
export const FISH_LIST_SUCCESS = 'FISH_LIST_SUCCESS';
export const FISH_LIST_FAIL = 'FISH_LIST_FAIL';